# Generated by Django 5.0.7 on 2024-08-31 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meraki_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
    ]
