# Generated by Django 5.0.7 on 2024-09-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meraki_app', '0002_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
